name: Publish to NPM
on:
  pull_request:
    types:
    - labeled
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.action == 'labeled' && github.event.label.name == 'release'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies and build 🔧
        run: npm ci && npm run build
      - name: Increment version ⬆️
        run: npm version patch
      - name: Publish package on NPM 📦
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}